"""
Project Management
==================

Handles project creation, saving, and loading.
"""

import json
import os
import uuid
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Optional

from .manim_integration import ManimSceneBuilder

class Project:
    """Represents a Manim UI project."""
    
    def __init__(self, name: str = "Untitled Project"):
        self.project_id = str(uuid.uuid4())
        self.name = name
        self.created_at = datetime.now()
        self.modified_at = datetime.now()
        self.file_path: Optional[str] = None
        
        # Project settings
        self.settings = {
            'resolution': '1920x1080',
            'frame_rate': 30,
            'quality': 'medium_quality',
            'background_color': '#2b2b2b',
            'default_animation_duration': 1.0
        }
        
        # Scene builder
        self.scene_builder = ManimSceneBuilder()
        
        # Metadata
        self.metadata = {
            'description': '',
            'author': '',
            'tags': [],
            'version': '1.0'
        }
    
    def save(self, file_path: Optional[str] = None) -> bool:
        """Save the project to a file."""
        if file_path:
            self.file_path = file_path
        
        if not self.file_path:
            return False
        
        try:
            self.modified_at = datetime.now()
            
            project_data = {
                'project_id': self.project_id,
                'name': self.name,
                'created_at': self.created_at.isoformat(),
                'modified_at': self.modified_at.isoformat(),
                'settings': self.settings,
                'metadata': self.metadata,
                'objects': {obj_id: obj.to_dict() for obj_id, obj in self.scene_builder.objects.items()},
                'animations': [anim.to_dict() for anim in self.scene_builder.animations],
                'scene_properties': self.scene_builder.scene_properties
            }
            
            # Ensure directory exists
            if os.path.dirname(self.file_path):
                os.makedirs(os.path.dirname(self.file_path), exist_ok=True)
            
            # Save to file
            with open(self.file_path, 'w') as f:
                json.dump(project_data, f, indent=2, default=str)
            
            return True
            
        except Exception as e:
            print(f"Error saving project: {e}")
            return False
    
    @classmethod
    def load(cls, file_path: str) -> Optional['Project']:
        """Load a project from a file."""
        try:
            with open(file_path, 'r') as f:
                project_data = json.load(f)
            
            # Create project instance
            project = cls(project_data.get('name', 'Loaded Project'))
            project.project_id = project_data.get('project_id', str(uuid.uuid4()))
            project.file_path = file_path
            
            # Parse dates
            created_str = project_data.get('created_at')
            if created_str:
                project.created_at = datetime.fromisoformat(created_str)
            
            modified_str = project_data.get('modified_at')
            if modified_str:
                project.modified_at = datetime.fromisoformat(modified_str)
            
            # Load settings and metadata
            project.settings.update(project_data.get('settings', {}))
            project.metadata.update(project_data.get('metadata', {}))
            
            # Load scene data
            project.scene_builder.load_project(file_path)
            
            return project
            
        except Exception as e:
            print(f"Error loading project: {e}")
            return None
    
    def export_manim_code(self, output_path: str) -> bool:
        """Export the project as a Manim Python script."""
        try:
            code = self.scene_builder.generate_manim_code()
            
            # Add header comment
            header = f'''"""
Generated Manim Scene
====================

Project: {self.name}
Generated by: Manim UI Builder
Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
"""

'''
            
            full_code = header + code
            
            with open(output_path, 'w') as f:
                f.write(full_code)
            
            return True
            
        except Exception as e:
            print(f"Error exporting code: {e}")
            return False
    
    def get_object_count(self) -> int:
        """Get the number of objects in the project."""
        return len(self.scene_builder.objects)
    
    def get_animation_count(self) -> int:
        """Get the number of animations in the project."""
        return len(self.scene_builder.animations)
    
    def get_duration(self) -> float:
        """Get the total duration of the project."""
        if not self.scene_builder.animations:
            return 0.0
        
        max_end_time = 0.0
        for anim in self.scene_builder.animations:
            end_time = anim.start_time + anim.duration
            max_end_time = max(max_end_time, end_time)
        
        return max_end_time

class ProjectManager:
    """Manages multiple projects and recent files."""
    
    def __init__(self):
        self.current_project: Optional[Project] = None
        self.recent_files: list = []
        self.config_dir = Path.home() / '.manim_ui'
        self.config_file = self.config_dir / 'config.json'
        
        # Create config directory if it doesn't exist
        self.config_dir.mkdir(exist_ok=True)
        
        # Load configuration
        self._load_config()
    
    def _load_config(self):
        """Load configuration from file."""
        if self.config_file.exists():
            try:
                with open(self.config_file, 'r') as f:
                    config = json.load(f)
                    self.recent_files = config.get('recent_files', [])
            except Exception as e:
                print(f"Error loading config: {e}")
                self.recent_files = []
    
    def _save_config(self):
        """Save configuration to file."""
        try:
            config = {
                'recent_files': self.recent_files
            }
            
            with open(self.config_file, 'w') as f:
                json.dump(config, f, indent=2)
                
        except Exception as e:
            print(f"Error saving config: {e}")
    
    def new_project(self, name: str = "New Project") -> Project:
        """Create a new project."""
        self.current_project = Project(name)
        return self.current_project
    
    def open_project(self, file_path: str) -> Optional[Project]:
        """Open an existing project."""
        project = Project.load(file_path)
        if project:
            self.current_project = project
            self._add_to_recent_files(file_path)
        
        return project
    
    def save_current_project(self, file_path: Optional[str] = None) -> bool:
        """Save the current project."""
        if not self.current_project:
            return False
        
        success = self.current_project.save(file_path)
        if success and self.current_project.file_path:
            self._add_to_recent_files(self.current_project.file_path)
        
        return success
    
    def close_current_project(self):
        """Close the current project."""
        self.current_project = None
    
    def _add_to_recent_files(self, file_path: str):
        """Add a file to the recent files list."""
        # Remove if already in list
        if file_path in self.recent_files:
            self.recent_files.remove(file_path)
        
        # Add to beginning
        self.recent_files.insert(0, file_path)
        
        # Keep only the last 10 files
        self.recent_files = self.recent_files[:10]
        
        # Save config
        self._save_config()
    
    def get_recent_files(self) -> list:
        """Get the list of recent files."""
        # Filter out files that no longer exist
        valid_files = []
        for file_path in self.recent_files:
            if os.path.exists(file_path):
                valid_files.append(file_path)
        
        self.recent_files = valid_files
        return self.recent_files